import { Permission, RoleDefinition } from '@/types/auth';
import { UserRole } from '@/types/database';

export const ROLE_DEFINITIONS: Record<UserRole, RoleDefinition> = {
  super_admin: {
    role: 'super_admin',
    name: 'Super Admin',
    description: 'Full global system administration across all churches and tenants.',
    badgeVariant: 'destructive',
    permissions: [
      'church:read',
      'church:update',
      'church:delete',
      'church:settings_update',
      'members:read',
      'members:create',
      'members:update',
      'members:delete',
      'members:view_sensitive',
      'families:read',
      'families:write',
      'ministries:read',
      'ministries:write',
      'groups:read',
      'groups:write',
      'groups:manage_roster',
      'volunteers:read',
      'volunteers:schedule',
      'attendance:read',
      'attendance:record',
      'events:read',
      'events:manage',
      'prayers:read_all',
      'prayers:read_team',
      'prayers:read_public',
      'prayers:submit',
      'prayers:manage',
      'follow_ups:read',
      'follow_ups:write',
      'follow_ups:assign',
      'follow_ups:delete',
      'finance:view_overview',
      'finance:view_detailed',
      'finance:manage_donations',
      'finance:manage_funds',
      'finance:view_statements',
      'finance:export_reports',
      'finance:view_audit_logs',
      'finance:view_own_giving',
      'announcements:read',
      'announcements:create',
      'announcements:manage',
      'communication:send',
      'children:read',
      'children:write',
      'children:check_in',
      'youth:read',
      'youth:manage',
      'reports:view',
      'audit_logs:view',
    ],
  },
  church_admin: {
    role: 'church_admin',
    name: 'Church Admin',
    description: 'Executive church administrator with full operational and settings authority.',
    badgeVariant: 'purple',
    permissions: [
      'church:read',
      'church:update',
      'church:settings_update',
      'members:read',
      'members:create',
      'members:update',
      'members:delete',
      'members:view_sensitive',
      'families:read',
      'families:write',
      'ministries:read',
      'ministries:write',
      'groups:read',
      'groups:write',
      'groups:manage_roster',
      'volunteers:read',
      'volunteers:schedule',
      'attendance:read',
      'attendance:record',
      'events:read',
      'events:manage',
      'prayers:read_all',
      'prayers:read_team',
      'prayers:read_public',
      'prayers:submit',
      'prayers:manage',
      'follow_ups:read',
      'follow_ups:write',
      'follow_ups:assign',
      'follow_ups:delete',
      'finance:view_overview',
      'finance:view_detailed',
      'finance:manage_donations',
      'finance:manage_funds',
      'finance:view_statements',
      'finance:export_reports',
      'finance:view_audit_logs',
      'finance:view_own_giving',
      'announcements:read',
      'announcements:create',
      'announcements:manage',
      'communication:send',
      'children:read',
      'children:write',
      'children:check_in',
      'youth:read',
      'youth:manage',
      'reports:view',
      'audit_logs:view',
    ],
  },
  pastor: {
    role: 'pastor',
    name: 'Pastor',
    description: 'Senior or associate pastor with full pastoral oversight, congregation care & spiritual records.',
    badgeVariant: 'default',
    permissions: [
      'church:read',
      'church:update',
      'church:settings_update',
      'members:read',
      'members:create',
      'members:update',
      'members:view_sensitive',
      'families:read',
      'families:write',
      'ministries:read',
      'ministries:write',
      'groups:read',
      'groups:write',
      'groups:manage_roster',
      'volunteers:read',
      'volunteers:schedule',
      'attendance:read',
      'attendance:record',
      'events:read',
      'events:manage',
      'prayers:read_all',
      'prayers:read_team',
      'prayers:read_public',
      'prayers:submit',
      'prayers:manage',
      'follow_ups:read',
      'follow_ups:write',
      'follow_ups:assign',
      'follow_ups:delete',
      'finance:view_overview',
      'finance:view_statements',
      'finance:view_own_giving',
      'announcements:read',
      'announcements:create',
      'announcements:manage',
      'communication:send',
      'children:read',
      'children:write',
      'children:check_in',
      'youth:read',
      'youth:manage',
      'reports:view',
    ],
  },
  ministry_leader: {
    role: 'ministry_leader',
    name: 'Ministry Leader',
    description: 'Leads a church department or ministry (e.g., Worship, Youth, Outreach, Prayer).',
    badgeVariant: 'emerald',
    permissions: [
      'church:read',
      'members:read',
      'families:read',
      'ministries:read',
      'ministries:write',
      'groups:read',
      'groups:write',
      'groups:manage_roster',
      'volunteers:read',
      'volunteers:schedule',
      'attendance:read',
      'attendance:record',
      'events:read',
      'events:manage',
      'prayers:read_team',
      'prayers:read_public',
      'prayers:submit',
      'prayers:manage',
      'follow_ups:read',
      'follow_ups:write',
      'finance:view_own_giving',
      'announcements:read',
      'announcements:create',
      'communication:send',
      'children:read',
      'children:write',
      'children:check_in',
      'youth:read',
      'youth:manage',
      'reports:view',
    ],
  },
  group_leader: {
    role: 'group_leader',
    name: 'Group Leader',
    description: 'Leads a small group, life group, or discipleship circle.',
    badgeVariant: 'amber',
    permissions: [
      'church:read',
      'members:read',
      'families:read',
      'ministries:read',
      'groups:read',
      'groups:write',
      'groups:manage_roster',
      'volunteers:read',
      'attendance:read',
      'attendance:record',
      'events:read',
      'prayers:read_public',
      'prayers:submit',
      'follow_ups:read',
      'follow_ups:write',
      'finance:view_own_giving',
      'announcements:read',
    ],
  },
  cell_group_leader: {
    role: 'cell_group_leader',
    name: 'Cell Group Leader',
    description: 'Leads an assigned cell group ministry, manages member rosters, and records attendance.',
    badgeVariant: 'amber',
    permissions: [
      'church:read',
      'members:read',
      'families:read',
      'ministries:read',
      'groups:read',
      'groups:write',
      'groups:manage_roster',
      'volunteers:read',
      'attendance:read',
      'attendance:record',
      'events:read',
      'prayers:read_public',
      'prayers:submit',
      'follow_ups:read',
      'follow_ups:write',
      'finance:view_own_giving',
      'announcements:read',
    ],
  },
  volunteer: {
    role: 'volunteer',
    name: 'Volunteer',
    description: 'Serves in Sunday services, welcome team, tech, or outreach events.',
    badgeVariant: 'secondary',
    permissions: [
      'church:read',
      'members:read',
      'ministries:read',
      'groups:read',
      'volunteers:read',
      'attendance:read',
      'events:read',
      'prayers:read_team',
      'prayers:read_public',
      'prayers:submit',
      'finance:view_own_giving',
      'announcements:read',
    ],
  },
  member: {
    role: 'member',
    name: 'Member',
    description: 'Congregation member with access to personal profile, family, group, giving, & prayer wall.',
    badgeVariant: 'outline',
    permissions: [
      'church:read',
      'groups:read',
      'events:read',
      'prayers:read_public',
      'prayers:submit',
      'finance:view_own_giving',
      'announcements:read',
    ],
  },
};

export const ROLE_HIERARCHY: Record<UserRole, number> = {
  super_admin: 100,
  church_admin: 90,
  pastor: 85,
  ministry_leader: 60,
  group_leader: 40,
  cell_group_leader: 40,
  volunteer: 20,
  member: 10,
};

export function hasPermission(role: UserRole | null | undefined, permission: Permission): boolean {
  if (!role) return false;
  const roleDef = ROLE_DEFINITIONS[role];
  if (!roleDef) return false;
  return roleDef.permissions.includes(permission);
}

export function hasAnyPermission(role: UserRole | null | undefined, permissions: Permission[]): boolean {
  if (!role) return false;
  return permissions.some((perm) => hasPermission(role, perm));
}

export function hasAllPermissions(role: UserRole | null | undefined, permissions: Permission[]): boolean {
  if (!role) return false;
  return permissions.every((perm) => hasPermission(role, perm));
}

export function isRoleAtLeast(currentRole: UserRole | null | undefined, targetRole: UserRole): boolean {
  if (!currentRole) return false;
  return (ROLE_HIERARCHY[currentRole] ?? 0) >= (ROLE_HIERARCHY[targetRole] ?? 0);
}
